rfcfold: support reading from STDIN etc.
If the provided input file is not a regular file, but, e.g., STDIN,
write the contents to a temporary file for further processing.  This
allows the use of `-i /dev/stdin` to read input from another process
via pipe, if /dev/stdin is supported by, e.g., the OS or the shell.
Manually tested on GNU/Linux from within a Bash and a dash shell.

diff --git a/rfcfold b/rfcfold
--- a/rfcfold
+++ b/rfcfold
@@ -76,6 +76,7 @@ col_gvn=0  # maxcol overridden?
 hdr_txt_1="NOTE: '\\' line wrapping per RFC 8792"
 hdr_txt_2="NOTE: '\\\\' line wrapping per RFC 8792"
 temp_dir=""
+temp_infile=""
 prog_name='rfcfold'
 prog_version='1.1.0'
 
@@ -110,7 +111,7 @@ type gsed > /dev/null 2>&1 && SED=gsed || SED=sed
 warn 'not using GNU `sed` (likely cause if an error occurs).'
 
 cleanup() {
-  rm -rf "$temp_dir"
+  rm -rf "$temp_dir" "$temp_infile"
 }
 trap 'cleanup' EXIT
 
@@ -358,9 +359,18 @@ process_input() {
     exit 1
   fi
 
-  if [[ ! -f "$infile" ]]; then
-    err "specified file '$infile' does not exist."
+  if [[ ! -e "$infile" ]]; then
+    err "specified infile '$infile' does not exist."
     exit 1
+  elif [[ ! -r "$infile" ]]; then
+    err "specified infile '$infile' cannot be read."
+    exit 1
+  elif [[ ! -f "$infile" ]]; then
+    dbg "specified infile '$infile' is not a regular file."
+    temp_infile=$(mktemp)
+    dbg "writing infile to temporary file."
+    cat "$infile" > "$temp_infile"
+    infile=$temp_infile
   fi
 
   if [[ "$col_gvn" -eq 1 ]] && [[ "$reversed" -eq 1 ]]; then
